# Generated by Django 3.0.4 on 2020-03-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='side',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
