# Generated by Django 3.0.4 on 2020-03-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='message',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
