# Generated by Django 3.0.4 on 2020-03-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='message',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
